language: c++
sudo: false
compiler: gcc
os:
  - linux
addons:
  apt:
    packages:
      - ninja-build
before_install:
  - gem update --system
  - gem install rake
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - rake rake host:test
notifications:
  email:
    on_success: change
    on_failure: change
