language: c++
sudo: required
dist: trusty

matrix:
  include:
    - compiler gcc
    addons:
      apt:
        packages:
          - gcc-5
          - g++-5
        env:
          - CC=gcc-5
          - CXX=g++-5


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev ninja-build
  - gem update --system
  - gem install rake
install:
  - rake install
script:
  - rake host:test
notifications:
  email:
    on_success: change
    on_failure: change
