language: c++
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
      - ninja-build
      - gcc-6
      - g++-6
    sources: &sources
        - ubuntu-toolchain-r-test

compiler: gcc-6

before_install:
  - export CC=gcc-6
  - export CXX=g++-6
  - gem update --system
  - gem install rake
install:
  - rake install
script:
  - $CC -v
  - rake host:test
notifications:
  email:
    on_success: change
    on_failure: change
