language: c++
sudo: false
compiler: gcc
os:
  - linux
before_install:
  - apt-get install ninja-build
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - rake rake host:test
notifications:
  email:
    on_success: change
    on_failure: change
