language: c++
sudo: required
dist: trusty
compiler: gcc
os:
  - linux
addons:
  apt:
    packages:
      - ninja-build
      - gcc-6
      - g++-6
    sources: &sources
        - ubuntu-toolchain-r-test
before_install:
  - gem update --system
  - gem install rake
install:
  - rake install
script:
  - g++ -v
  - rake host:test
notifications:
  email:
    on_success: change
    on_failure: change
